{"response_code":0,"results":[
{"type":"multiple","difficulty":"medium","category":"1",
"ans":"The Amazon River and its tributaries make it the largest drainage system in the world by discharge volume, there are over 15000 tributaries.",
"question":" Which river of the world has the maximum number of branches?",
"correct_answer":"Amazon River","incorrect_answers":["Mississippi River","Nile River","Yangtze River"]},
{"type":"multiple","difficulty":"hard","category":"2",
"question":"How long is the world's largest beaver dam?",
"ans":"Clair Beaver Dam is a true testament to the beavers determination and ingenuity. Spanning an incredible length of approximately 850 meters (2,790 feet), it is the largest beaver dam ever recorded.",
"correct_answer":"850m","incorrect_answers":["85m","170m ","1700m"]},
{"type":"multiple","difficulty":"medium","category":"3",
"question":"What is the flow of land into the body of water?",
"ans":"Run-off refers to the movement of water from land surfaces into bodies of water such as rivers, lakes, and oceans.",
"correct_answer":"Run-off","incorrect_answers":["Groundwater","Infiltration","Headwaters"]},
{"type":"multiple","difficulty":"medium","category":"4",
"ans":"So far the most common limiting nutrients are nitrogen and phosphorus. Why? Because these are essential for growth (to form DNA, proteins etc) but are not always present in abundant supply in the water. Carbon, hydrogen and oxygen are also essential, but the carbon comes from almost limitless dissolved carbon dioxide, and hydrogen and oxygen from the water itself.",
"question":"Which two non-metals are most commonly found to limit plant growth when all other conditions are conducive for growth?",
"correct_answer":"N and P","incorrect_answers":["S and Cl","N and S","P and Cl"]},
{"type":"multiple","difficulty":"medium","category":"5",
"ans":"The Congo is the deepest river in the world. It is 1760 metres above sea level, flows into the Atlantic Ocean.",
"question":"What is the deepest river in the world?",
"correct_answer":"Congo River","incorrect_answers":["Amazon River","Yellow River","Yenisei River"]},
{"type":"multiple","difficulty":"medium","category":"6",
"ans":"A buffer is a substance that typically has significant proportions of both acid and base forms present. When another acid or base is added to the water, this causes a change in the relative proportions of the buffer's forms which in turn minimizes induced change in pH. If the pKa of the buffer is 5 and an acid is added, then the final pH will be a little less than 5.",
"question":"Buffering capacity is an important factor describing the behavior of aquatic ecosystems. What is the best definition of a 'buffer'?",
"correct_answer":"A substance that minimizes change in pH when an acid or base is added","incorrect_answers":["A substance that makes the solution more alkaline","A substance that polishes pollutants from the water","A substance that makes the pH closer to neutral"]},
{"type":"multiple","difficulty":"medium","category":"7",
"ans":"Recharge can occur from the infiltration of rainfall, river/pond leakage, or even artificially by injection wells or specially designed recharge pits.",
"question":"What term describes the infiltration of water from the surface to the water table?",
"correct_answer":"Recharge","incorrect_answers":["Through-flow","Permeation","Base-flow"]},
{"type":"multiple","difficulty":"easy","category":"8",
"ans":"The upper course of Neretva, Upper Neretva has water of Class I purity and is almost certainly the coldest river water in the world, often as low as 7-8 degrees Celsius in the summer months.",
"question":"Which Is The Coldest River In The World?",
"correct_answer":"Neretva River","incorrect_answers":["Yukon River","Ob River","Amur River"]},
{"type":"multiple","difficulty":"easy","category":"9",
"ans":"The Danube river in Europe passes through 10 countries: Germany, Hungary, Romania, Austria, Serbia, Bulgaria, Croatia, Moldova, Ukraine, Slovakia. It starts in Southern Germany and runs into the Black Sea through Romania.",
"question":"Which river passes through maximum number of countries?",
"correct_answer":"Danube river","incorrect_answers":["Mekong River","Rhine River","Nile River"]},
{"type":"multiple","difficulty":"medium","category":"10",
"ans":"A more useful term is 'specific yield'. This is similar to porosity, but does not include the amount of water that cannot be drained due to capillary forces.",
"question":"The percentage of water that can be stored in a rock, compared to the aggregate volume of the whole rock, is called what?",
"correct_answer":"Porosity","incorrect_answers":["Storativity","Permeability","Transmissivity"]},
{"type":"multiple","difficulty":"easy","category":"11",
"ans":"Rain water, which falls in the area above the main vent of the volcano, is evaporated by the heat, and then quickly condenses, forming a lake which covers the main vent of the volcano. As it covers the main vent, volcanic lakes often have sulphur floating on their surface.",
"question":"Which of these descriptions most accurately describes a crater lake?",
"correct_answer":"A cap of meteoric water covering the main vent of a volcano, found in only 12% of all Holocene-aged volcanoes.","incorrect_answers":["The caldera of a volcano filled with rainwater caught by a thin veil of solid magma atop the main vent.","Water formed by the volcano heating and cooling, caught by the vegetation either side of the caldera and collected.","A lake found in the crater of an extinct or dormant volcano, similar to a cwm or corrie."]},
{"type":"multiple","difficulty":"medium","category":"12",
"ans":"Canada has about 1.29 million km2 of wetlands, covering 13% of Canada's terrestrial area. This is close to one quarter of the world's remaining wetland.",
"question":"What percentage of Canada's land area is covered in wetlands?",
"correct_answer":"13%","incorrect_answers":["23%","30%","33%"]},
{"type":"multiple","difficulty":"easy","category":"13",
"ans":"Many birds use the prairie potholes as breeding grounds, and resting places during winter migrations.",
"question":"Which wetland is found in the grasslands of central North America?",
"correct_answer":"prairie pothole","incorrect_answers":["soggy wheatfield","vernal pools","silty sedgeland"]},
{"type":"multiple","difficulty":"medium","category":"14",
"ans":"Cypress trees have knees. Knees were once thought to help bring oxygen from the air to the plant roots.",
"question":"What is a part of the root of a wetlands tree which emerges from the water in which the tree is growing?",
"correct_answer":"knee","incorrect_answers":["bench","buttress","rhizome"]},
{"type":"multiple","difficulty":"medium","category":"15",
"ans":"An isobar map shows air pressure, isohyet shows rainfall, an isobath shows ocean depth.",
"question":"The thickness of an aquifer may be represented on what kind of a map?",
"correct_answer":"Isopach","incorrect_answers":["Isobar","Isohyet","Isobath"]},
{"type":"multiple","difficulty":"medium","category":"16",
"ans":"These two bass species are quite similar. One way to tell the difference is their actual size. Largemouth bass can grow larger than ten pounds (4.5 kg) while smallmouth bass do not grow larger than that. You can also check the jaw - largemouth upper jaws extend above the eye when open, while smallmouth upper jaws remain level with the eye when open. Largemouth bass also have a deep notch between their two dorsal fins while smallmouth bass have no notch between the dorsal fins. Finally, largemouth bass have a greenish body with horizontal lines, while smallmouth bass have a brownish body with vertical lines.",
"question":"What are the three main things to check to tell the difference between largemouth bass and smallmouth bass?",
"correct_answer":"Jaw, dorsal fin, colour","incorrect_answers":["Jaw, dorsal fin, teeth","Jaw, tail fin, colour","Jaw, eye placement, teeth"]},
{"type":"multiple","difficulty":"medium","category":"17",
"ans":"The lake trout in Lake Diefenbaker were accidentally released from a fish farm where they had been genetically modified to grow larger.The fish are sterile, so all energy that would normally go towards reproduction is used for growth.",
"question":"Why is the typical size of lake trout much larger in Lake Diefenbaker, Saskatchewan than in most other parts of the world?",
"correct_answer":"The fish are genetically modified","incorrect_answers":["More sunlight in the area means an abundance of natural food","No predators in the lake so the trout grow much larger than normal","Locals prepare a secret recipe and feed the fish twice daily"]},
{"type":"multiple","difficulty":"medium","category":"18",
"ans":"Poison sumac, poison ivy, stinging nettle: it is well worth the effort to learn to identify these three species. Poison sumac and poison ivy can send you to the hospital or just cause you misery. Stinging nettles will cause discomfort.",
"question":"Some wetland plants can harm humans, or at least cause them discomfort. Which can not?",
"correct_answer":"Venus flytrap","incorrect_answers":["Stinging nettle","Poison sumac","Poison ivy"]},
{"type":"multiple","difficulty":"medium","category":"19",
"ans":"Jack pine is widespread throughout Northwestern Ontario, commonly found on sandy soils, and shallow soil over bedrock",
"question":"Which of the following trees is not common in wetlands?",
"correct_answer":"Jack pine","incorrect_answers":["Box elder","Yellow Birch","Green Ash"]},
{"type":"multiple","difficulty":"easy","category":"20",
"ans":"Pitcher plant is insectivorous, but is not submergent. Stinging nettle does not use its sting to capture insects.",
"question":"This submergent wetland plant is insectivorous:",
"correct_answer":"Bladderwort","incorrect_answers":["Duckweed","Pitcher plant","Stinging nettle"]}
]}